name: Kick Auto Logger

on:
  schedule:
    - cron: '*/30 * * * *' # هذي تعني: اشتغل كل 30 دقيقة طوال اليوم
  workflow_dispatch: # زر يسمح لك بتشغيله يدوياً للتجربة

jobs:
  update-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Requests
        run: pip install requests

      - name: Run Scraper
        run: python update_data.py # تشغيل السكربت اللي صنعناه

      - name: Commit and Push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add streams.json
          git commit -m "تحديث تلقائي للساعات [skip ci]" || exit 0
          git push